name: ZenMaps
favicon: null
layout_spectrum: 0.92131
typography_spectrum: 0.91209
title: ZenMaps
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#a18a78'
    - '#cdbba7'
    - '#7b624c'
    - '#eee2d2'
    - '#2d0d06'
  brandStrength: 0.25
  lightness: 0.125
  saturation: 0
  rhythmicContrast: 0
purpose: []
