name: ZenMaps
favicon: null
layout_spectrum: 0.81726178037934
typography_spectrum: 0.45067
title: ZenMaps
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.3372715129517019
  lightness: 0.07589099649339914
  saturation: 0
  rhythmicContrast: 0.09684258280321956
purpose: []
